kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-test
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
       storage: 10G  #TODO: specify the appropriate size to match pv in pool of ceph rbd
  storageClassName: wangsucloud-standard

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: nginx-test
  name: nginx-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-test
        ws_pod_deployment: nginx-test
      name: nginx-test
    spec:
      containers:
      - image: gd04cr-internal.wangsucloud.com/wgb-test1/nginx-test:v2
        imagePullPolicy: Always
        name: nginx-test
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - mountPath: /data/nginx-test/
          name: pvc-nginx-test
        imagePullSecrets:
        - name: secret-wangsu2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pvc-nginx-test
        persistentVolumeClaim:
          claimName: nginx-test

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    loadbalancer.wangsucloud.com/connection-limit: "5000"
    service.beta.kubernetes.io/wangsucloud-internal-load-balancer: "false"
    wangsucloud.com/bandwidth: "1"
    wangsucloud.com/bss-period: hour
  name: nginx-test
  namespace: default
spec:
  ports:
  - name: nginx-test-8080-80
    nodePort: 31310
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-test
  type: LoadBalancer
